### ISSUE TITLE
Gitignore

### ISSUE THREAD

**Issue by soggybag** [kendrajmoore/redditclone#10]
Add a gitignore that ignores node_modules. You shouldn't upload the entire node_modules folder. 

https://chaseadams.io/2015/07/my-gitignore-conventions/

Instead anyone downloading or forking your project should be able to load the modules by running `npm install` themselves. Include instructions on how to do this in your readme.

**Comment by kendrajmoore** [comment]
done

**Comment by soggybag** [comment]
Close an issue with the "Close and comment" button below.
